/*
 * Clerk Frontend API
 *
 * The Clerk REST Frontend API, meant to be accessed from a browser or native environment.  This is a Form Based API and all the data must be sent and formatted according to the `application/x-www-form-urlencoded` content type.  ### Versions  When the API changes in a way that isn't compatible with older versions, a new version is released. Each version is identified by its release date, e.g. `2021-02-05`. For more information, please see [Clerk API Versions](https://clerk.com/docs/backend-requests/versioning/overview).  ### Using the Try It Console  The `Try It` feature of the docs only works for **Development Instances** when using the `DevBrowser` security scheme. To use it, first generate a dev instance token from the `/v1/dev_browser` endpoint.  Please see https://clerk.com/docs for more information.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@clerk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetProxyHealth200Response {
    GetProxyHealth200ResponseOneOf(Box<models::GetProxyHealth200ResponseOneOf>),
    GetHealth503Response(Box<models::GetHealth503Response>),
    /// scriptoria patch: 未知の shape (新 verification strategy 等) を
    /// graceful に受ける forward-compat フォールバック。
    Unknown(serde_json::Value),
}

impl Default for GetProxyHealth200Response {
    fn default() -> Self {
        Self::GetProxyHealth200ResponseOneOf(Default::default())
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "unhealthy")]
    Unhealthy,
    /// scriptoria patch: 未知バリアントを graceful に受ける forward-compat フォールバック
    #[serde(other)]
    Unknown,
}

impl Default for Status {
    fn default() -> Status {
        Self::Unhealthy
    }
}
